module.exports = [
    {
        "transactionID": "10001",
        "date": "1/1/2024",
        "productCategory": "Electronics",
        "productName": "iPhone 14 Pro",
        "unitsSold": "2",
        "unitPrice": "999.99",
        "totalRevenue": "1999.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10002",
        "date": "2/1/2024",
        "productCategory": "Home Appliances",
        "productName": "Dyson V11 Vacuum",
        "unitsSold": "1",
        "unitPrice": "499.99",
        "totalRevenue": "499.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10003",
        "date": "3/1/2024",
        "productCategory": "Clothing",
        "productName": "Levi's 501 Jeans",
        "unitsSold": "3",
        "unitPrice": "69.99",
        "totalRevenue": "209.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10004",
        "date": "4/1/2024",
        "productCategory": "Books",
        "productName": "The Da Vinci Code",
        "unitsSold": "4",
        "unitPrice": "15.99",
        "totalRevenue": "63.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10005",
        "date": "5/1/2024",
        "productCategory": "Beauty Products",
        "productName": "Neutrogena Skincare Set",
        "unitsSold": "1",
        "unitPrice": "89.99",
        "totalRevenue": "89.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10006",
        "date": "6/1/2024",
        "productCategory": "Sports",
        "productName": "Wilson Evolution Basketball",
        "unitsSold": "5",
        "unitPrice": "29.99",
        "totalRevenue": "149.95",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10007",
        "date": "7/1/2024",
        "productCategory": "Electronics",
        "productName": "MacBook Pro 16-inch",
        "unitsSold": "1",
        "unitPrice": "2499.99",
        "totalRevenue": "2499.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10008",
        "date": "8/1/2024",
        "productCategory": "Home Appliances",
        "productName": "Blueair Classic 480i",
        "unitsSold": "2",
        "unitPrice": "599.99",
        "totalRevenue": "1199.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10009",
        "date": "9/1/2024",
        "productCategory": "Clothing",
        "productName": "Nike Air Force 1",
        "unitsSold": "6",
        "unitPrice": "89.99",
        "totalRevenue": "539.94",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10010",
        "date": "10/1/2024",
        "productCategory": "Books",
        "productName": "Dune by Frank Herbert",
        "unitsSold": "2",
        "unitPrice": "25.99",
        "totalRevenue": "51.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10011",
        "date": "11/1/2024",
        "productCategory": "Beauty Products",
        "productName": "Chanel No. 5 Perfume",
        "unitsSold": "1",
        "unitPrice": "129.99",
        "totalRevenue": "129.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10012",
        "date": "12/1/2024",
        "productCategory": "Sports",
        "productName": "Babolat Pure Drive Tennis Racket",
        "unitsSold": "3",
        "unitPrice": "199.99",
        "totalRevenue": "599.97",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10013",
        "date": "13/1/2024",
        "productCategory": "Electronics",
        "productName": "Samsung Galaxy Tab S8",
        "unitsSold": "2",
        "unitPrice": "749.99",
        "totalRevenue": "1499.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10014",
        "date": "14/1/2024",
        "productCategory": "Home Appliances",
        "productName": "Keurig K-Elite Coffee Maker",
        "unitsSold": "1",
        "unitPrice": "189.99",
        "totalRevenue": "189.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10015",
        "date": "15/1/2024",
        "productCategory": "Clothing",
        "productName": "North Face Down Jacket",
        "unitsSold": "2",
        "unitPrice": "249.99",
        "totalRevenue": "499.98",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10016",
        "date": "16/1/2024",
        "productCategory": "Books",
        "productName": "\"Salt",
        "unitsSold": "4",
        "unitPrice": "100",
        "totalRevenue": " Heat by Samin Nosrat\"",
        "region": "3",
        "paymentMethod": "35.99"
    },
    {
        "transactionID": "10017",
        "date": "17/1/2024",
        "productCategory": "Beauty Products",
        "productName": "Dyson Supersonic Hair Dryer",
        "unitsSold": "1",
        "unitPrice": "399.99",
        "totalRevenue": "399.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10018",
        "date": "18/1/2024",
        "productCategory": "Sports",
        "productName": "Manduka PRO Yoga Mat",
        "unitsSold": "4",
        "unitPrice": "119.99",
        "totalRevenue": "479.96",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10019",
        "date": "19/1/2024",
        "productCategory": "Electronics",
        "productName": "Garmin Forerunner 945",
        "unitsSold": "2",
        "unitPrice": "499.99",
        "totalRevenue": "999.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10020",
        "date": "20/1/2024",
        "productCategory": "Home Appliances",
        "productName": "Ninja Professional Blender",
        "unitsSold": "1",
        "unitPrice": "99.99",
        "totalRevenue": "99.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10021",
        "date": "21/1/2024",
        "productCategory": "Clothing",
        "productName": "Zara Summer Dress",
        "unitsSold": "3",
        "unitPrice": "59.99",
        "totalRevenue": "179.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10022",
        "date": "22/1/2024",
        "productCategory": "Books",
        "productName": "Gone Girl by Gillian Flynn",
        "unitsSold": "2",
        "unitPrice": "22.99",
        "totalRevenue": "45.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10023",
        "date": "23/1/2024",
        "productCategory": "Beauty Products",
        "productName": "Olay Regenerist Face Cream",
        "unitsSold": "1",
        "unitPrice": "49.99",
        "totalRevenue": "49.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10024",
        "date": "24/1/2024",
        "productCategory": "Sports",
        "productName": "Adidas FIFA World Cup Football",
        "unitsSold": "3",
        "unitPrice": "29.99",
        "totalRevenue": "89.97",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10025",
        "date": "25/1/2024",
        "productCategory": "Electronics",
        "productName": "Bose QuietComfort 35 Headphones",
        "unitsSold": "1",
        "unitPrice": "299.99",
        "totalRevenue": "299.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10026",
        "date": "26/1/2024",
        "productCategory": "Home Appliances",
        "productName": "Panasonic NN-SN966S Microwave",
        "unitsSold": "1",
        "unitPrice": "179.99",
        "totalRevenue": "179.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10027",
        "date": "27/1/2024",
        "productCategory": "Clothing",
        "productName": "Adidas Ultraboost Shoes",
        "unitsSold": "2",
        "unitPrice": "179.99",
        "totalRevenue": "359.98",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10028",
        "date": "28/1/2024",
        "productCategory": "Books",
        "productName": "Pride and Prejudice by Jane Austen",
        "unitsSold": "3",
        "unitPrice": "12.99",
        "totalRevenue": "38.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10029",
        "date": "29/1/2024",
        "productCategory": "Beauty Products",
        "productName": "MAC Ruby Woo Lipstick",
        "unitsSold": "1",
        "unitPrice": "29.99",
        "totalRevenue": "29.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10030",
        "date": "30/1/2024",
        "productCategory": "Sports",
        "productName": "Nike Air Zoom Pegasus 37",
        "unitsSold": "2",
        "unitPrice": "129.99",
        "totalRevenue": "259.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10031",
        "date": "31/1/2024",
        "productCategory": "Electronics",
        "productName": "Sony WH-1000XM4 Headphones",
        "unitsSold": "2",
        "unitPrice": "349.99",
        "totalRevenue": "699.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10032",
        "date": "1/2/2024",
        "productCategory": "Home Appliances",
        "productName": "Instant Pot Duo",
        "unitsSold": "3",
        "unitPrice": "89.99",
        "totalRevenue": "269.97",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10033",
        "date": "2/2/2024",
        "productCategory": "Clothing",
        "productName": "Under Armour HeatGear T-Shirt",
        "unitsSold": "5",
        "unitPrice": "29.99",
        "totalRevenue": "149.95",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10034",
        "date": "3/2/2024",
        "productCategory": "Books",
        "productName": "1984 by George Orwell",
        "unitsSold": "4",
        "unitPrice": "19.99",
        "totalRevenue": "79.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10035",
        "date": "4/2/2024",
        "productCategory": "Beauty Products",
        "productName": "L'Oreal Revitalift Serum",
        "unitsSold": "2",
        "unitPrice": "39.99",
        "totalRevenue": "79.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10036",
        "date": "5/2/2024",
        "productCategory": "Sports",
        "productName": "Peloton Bike",
        "unitsSold": "1",
        "unitPrice": "1895",
        "totalRevenue": "1895",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10037",
        "date": "6/2/2024",
        "productCategory": "Electronics",
        "productName": "Apple Watch Series 8",
        "unitsSold": "3",
        "unitPrice": "399.99",
        "totalRevenue": "1199.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10038",
        "date": "7/2/2024",
        "productCategory": "Home Appliances",
        "productName": "Roomba i7+",
        "unitsSold": "2",
        "unitPrice": "799.99",
        "totalRevenue": "1599.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10039",
        "date": "8/2/2024",
        "productCategory": "Clothing",
        "productName": "Columbia Fleece Jacket",
        "unitsSold": "4",
        "unitPrice": "59.99",
        "totalRevenue": "239.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10040",
        "date": "9/2/2024",
        "productCategory": "Books",
        "productName": "Harry Potter and the Sorcerer's Stone",
        "unitsSold": "3",
        "unitPrice": "24.99",
        "totalRevenue": "74.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10041",
        "date": "10/2/2024",
        "productCategory": "Beauty Products",
        "productName": "Estee Lauder Advanced Night Repair",
        "unitsSold": "1",
        "unitPrice": "105",
        "totalRevenue": "105",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10042",
        "date": "11/2/2024",
        "productCategory": "Sports",
        "productName": "Fitbit Charge 5",
        "unitsSold": "2",
        "unitPrice": "129.99",
        "totalRevenue": "259.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10043",
        "date": "12/2/2024",
        "productCategory": "Electronics",
        "productName": "GoPro HERO10 Black",
        "unitsSold": "3",
        "unitPrice": "399.99",
        "totalRevenue": "1199.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10044",
        "date": "13/2/2024",
        "productCategory": "Home Appliances",
        "productName": "Nespresso VertuoPlus",
        "unitsSold": "1",
        "unitPrice": "199.99",
        "totalRevenue": "199.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10045",
        "date": "14/2/2024",
        "productCategory": "Clothing",
        "productName": "Patagonia Better Sweater",
        "unitsSold": "2",
        "unitPrice": "139.99",
        "totalRevenue": "279.98",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10046",
        "date": "15/2/2024",
        "productCategory": "Books",
        "productName": "Becoming by Michelle Obama",
        "unitsSold": "4",
        "unitPrice": "32.5",
        "totalRevenue": "130",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10047",
        "date": "16/2/2024",
        "productCategory": "Beauty Products",
        "productName": "Clinique Moisture Surge",
        "unitsSold": "1",
        "unitPrice": "52",
        "totalRevenue": "52",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10048",
        "date": "17/2/2024",
        "productCategory": "Sports",
        "productName": "Yeti Rambler Tumbler",
        "unitsSold": "6",
        "unitPrice": "39.99",
        "totalRevenue": "239.94",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10049",
        "date": "18/2/2024",
        "productCategory": "Electronics",
        "productName": "Kindle Paperwhite",
        "unitsSold": "2",
        "unitPrice": "129.99",
        "totalRevenue": "259.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10050",
        "date": "19/2/2024",
        "productCategory": "Home Appliances",
        "productName": "Breville Smart Oven",
        "unitsSold": "1",
        "unitPrice": "299.99",
        "totalRevenue": "299.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10051",
        "date": "20/2/2024",
        "productCategory": "Clothing",
        "productName": "Ray-Ban Aviator Sunglasses",
        "unitsSold": "3",
        "unitPrice": "154.99",
        "totalRevenue": "464.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10052",
        "date": "21/2/2024",
        "productCategory": "Books",
        "productName": "The Silent Patient by Alex Michaelides",
        "unitsSold": "2",
        "unitPrice": "26.99",
        "totalRevenue": "53.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10053",
        "date": "22/2/2024",
        "productCategory": "Beauty Products",
        "productName": "Shiseido Ultimate Sun Protector",
        "unitsSold": "1",
        "unitPrice": "49",
        "totalRevenue": "49",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10054",
        "date": "23/2/2024",
        "productCategory": "Sports",
        "productName": "Titleist Pro V1 Golf Balls",
        "unitsSold": "5",
        "unitPrice": "49.99",
        "totalRevenue": "249.95",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10055",
        "date": "24/2/2024",
        "productCategory": "Electronics",
        "productName": "Anker PowerCore Portable Charger",
        "unitsSold": "4",
        "unitPrice": "59.99",
        "totalRevenue": "239.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10056",
        "date": "25/2/2024",
        "productCategory": "Home Appliances",
        "productName": "KitchenAid Artisan Stand Mixer",
        "unitsSold": "1",
        "unitPrice": "499.99",
        "totalRevenue": "499.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10057",
        "date": "26/2/2024",
        "productCategory": "Clothing",
        "productName": "Calvin Klein Boxer Briefs",
        "unitsSold": "5",
        "unitPrice": "29.99",
        "totalRevenue": "149.95",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10058",
        "date": "27/2/2024",
        "productCategory": "Books",
        "productName": "Educated by Tara Westover",
        "unitsSold": "3",
        "unitPrice": "28",
        "totalRevenue": "84",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10059",
        "date": "28/2/2024",
        "productCategory": "Beauty Products",
        "productName": "Anastasia Beverly Hills Brow Wiz",
        "unitsSold": "2",
        "unitPrice": "23",
        "totalRevenue": "46",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10060",
        "date": "29/2/2024",
        "productCategory": "Sports",
        "productName": "Hyperice Hypervolt Massager",
        "unitsSold": "1",
        "unitPrice": "349",
        "totalRevenue": "349",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10061",
        "date": "1/3/2024",
        "productCategory": "Electronics",
        "productName": "Nintendo Switch",
        "unitsSold": "3",
        "unitPrice": "299.99",
        "totalRevenue": "899.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10062",
        "date": "2/3/2024",
        "productCategory": "Home Appliances",
        "productName": "Philips Airfryer XXL",
        "unitsSold": "2",
        "unitPrice": "199.99",
        "totalRevenue": "399.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10063",
        "date": "3/3/2024",
        "productCategory": "Clothing",
        "productName": "Hanes ComfortSoft T-Shirt",
        "unitsSold": "10",
        "unitPrice": "9.99",
        "totalRevenue": "99.9",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10064",
        "date": "4/3/2024",
        "productCategory": "Books",
        "productName": "Where the Crawdads Sing by Delia Owens",
        "unitsSold": "4",
        "unitPrice": "18.99",
        "totalRevenue": "75.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10065",
        "date": "5/3/2024",
        "productCategory": "Beauty Products",
        "productName": "Lancome La Vie Est Belle",
        "unitsSold": "1",
        "unitPrice": "102",
        "totalRevenue": "102",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10066",
        "date": "6/3/2024",
        "productCategory": "Sports",
        "productName": "Garmin Edge 530",
        "unitsSold": "2",
        "unitPrice": "299.99",
        "totalRevenue": "599.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10067",
        "date": "7/3/2024",
        "productCategory": "Electronics",
        "productName": "Samsung QLED 4K TV",
        "unitsSold": "1",
        "unitPrice": "1199.99",
        "totalRevenue": "1199.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10068",
        "date": "8/3/2024",
        "productCategory": "Home Appliances",
        "productName": "Eufy RoboVac 11S",
        "unitsSold": "3",
        "unitPrice": "219.99",
        "totalRevenue": "659.97",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10069",
        "date": "9/3/2024",
        "productCategory": "Clothing",
        "productName": "Puma Suede Classic Sneakers",
        "unitsSold": "4",
        "unitPrice": "59.99",
        "totalRevenue": "239.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10070",
        "date": "10/3/2024",
        "productCategory": "Books",
        "productName": "The Great Gatsby by F. Scott Fitzgerald",
        "unitsSold": "2",
        "unitPrice": "10.99",
        "totalRevenue": "21.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10071",
        "date": "11/3/2024",
        "productCategory": "Beauty Products",
        "productName": "Drunk Elephant C-Firma Day Serum",
        "unitsSold": "1",
        "unitPrice": "78",
        "totalRevenue": "78",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10072",
        "date": "12/3/2024",
        "productCategory": "Sports",
        "productName": "Nike Metcon 6",
        "unitsSold": "3",
        "unitPrice": "129.99",
        "totalRevenue": "389.97",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10073",
        "date": "13/3/2024",
        "productCategory": "Electronics",
        "productName": "HP Spectre x360 Laptop",
        "unitsSold": "1",
        "unitPrice": "1599.99",
        "totalRevenue": "1599.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10074",
        "date": "14/3/2024",
        "productCategory": "Home Appliances",
        "productName": "De'Longhi Magnifica Espresso Machine",
        "unitsSold": "1",
        "unitPrice": "899.99",
        "totalRevenue": "899.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10075",
        "date": "15/3/2024",
        "productCategory": "Clothing",
        "productName": "Tommy Hilfiger Polo Shirt",
        "unitsSold": "5",
        "unitPrice": "49.99",
        "totalRevenue": "249.95",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10076",
        "date": "16/3/2024",
        "productCategory": "Books",
        "productName": "To Kill a Mockingbird by Harper Lee",
        "unitsSold": "4",
        "unitPrice": "14.99",
        "totalRevenue": "59.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10077",
        "date": "17/3/2024",
        "productCategory": "Beauty Products",
        "productName": "Glossier Boy Brow",
        "unitsSold": "2",
        "unitPrice": "16",
        "totalRevenue": "32",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10078",
        "date": "18/3/2024",
        "productCategory": "Sports",
        "productName": "Rogue Fitness Kettlebell",
        "unitsSold": "3",
        "unitPrice": "69.99",
        "totalRevenue": "209.97",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10079",
        "date": "19/3/2024",
        "productCategory": "Electronics",
        "productName": "Apple AirPods Pro",
        "unitsSold": "2",
        "unitPrice": "249.99",
        "totalRevenue": "499.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10080",
        "date": "20/3/2024",
        "productCategory": "Home Appliances",
        "productName": "Dyson Pure Cool Link",
        "unitsSold": "1",
        "unitPrice": "499.99",
        "totalRevenue": "499.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10081",
        "date": "21/3/2024",
        "productCategory": "Clothing",
        "productName": "Levi's Trucker Jacket",
        "unitsSold": "2",
        "unitPrice": "89.99",
        "totalRevenue": "179.98",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10082",
        "date": "22/3/2024",
        "productCategory": "Books",
        "productName": "The Hobbit by J.R.R. Tolkien",
        "unitsSold": "3",
        "unitPrice": "12.99",
        "totalRevenue": "38.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10083",
        "date": "23/3/2024",
        "productCategory": "Beauty Products",
        "productName": "Charlotte Tilbury Magic Cream",
        "unitsSold": "1",
        "unitPrice": "100",
        "totalRevenue": "100",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10084",
        "date": "24/3/2024",
        "productCategory": "Sports",
        "productName": "Spalding NBA Street Basketball",
        "unitsSold": "6",
        "unitPrice": "24.99",
        "totalRevenue": "149.94",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10085",
        "date": "25/3/2024",
        "productCategory": "Electronics",
        "productName": "Ring Video Doorbell",
        "unitsSold": "1",
        "unitPrice": "99.99",
        "totalRevenue": "99.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10086",
        "date": "26/3/2024",
        "productCategory": "Home Appliances",
        "productName": "LG OLED TV",
        "unitsSold": "2",
        "unitPrice": "1299.99",
        "totalRevenue": "2599.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10087",
        "date": "27/3/2024",
        "productCategory": "Clothing",
        "productName": "Uniqlo Ultra Light Down Jacket",
        "unitsSold": "3",
        "unitPrice": "79.99",
        "totalRevenue": "239.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10088",
        "date": "28/3/2024",
        "productCategory": "Books",
        "productName": "The Catcher in the Rye by J.D. Salinger",
        "unitsSold": "4",
        "unitPrice": "13.99",
        "totalRevenue": "55.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10089",
        "date": "29/3/2024",
        "productCategory": "Beauty Products",
        "productName": "Sunday Riley Good Genes",
        "unitsSold": "1",
        "unitPrice": "105",
        "totalRevenue": "105",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10090",
        "date": "30/3/2024",
        "productCategory": "Sports",
        "productName": "On Running Cloud Shoes",
        "unitsSold": "2",
        "unitPrice": "129.99",
        "totalRevenue": "259.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10091",
        "date": "31/3/2024",
        "productCategory": "Electronics",
        "productName": "Logitech MX Master 3 Mouse",
        "unitsSold": "2",
        "unitPrice": "99.99",
        "totalRevenue": "199.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10092",
        "date": "1/4/2024",
        "productCategory": "Home Appliances",
        "productName": "Instant Pot Duo Crisp",
        "unitsSold": "1",
        "unitPrice": "179.99",
        "totalRevenue": "179.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10093",
        "date": "2/4/2024",
        "productCategory": "Clothing",
        "productName": "Adidas Originals Superstar Sneakers",
        "unitsSold": "4",
        "unitPrice": "79.99",
        "totalRevenue": "319.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10094",
        "date": "3/4/2024",
        "productCategory": "Books",
        "productName": "The Alchemist by Paulo Coelho",
        "unitsSold": "3",
        "unitPrice": "14.99",
        "totalRevenue": "44.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10095",
        "date": "4/4/2024",
        "productCategory": "Beauty Products",
        "productName": "Tatcha The Water Cream",
        "unitsSold": "1",
        "unitPrice": "68",
        "totalRevenue": "68",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10096",
        "date": "5/4/2024",
        "productCategory": "Sports",
        "productName": "Garmin Fenix 6X Pro",
        "unitsSold": "1",
        "unitPrice": "999.99",
        "totalRevenue": "999.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10097",
        "date": "6/4/2024",
        "productCategory": "Electronics",
        "productName": "Bose SoundLink Revolve+ Speaker",
        "unitsSold": "3",
        "unitPrice": "299.99",
        "totalRevenue": "899.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10098",
        "date": "7/4/2024",
        "productCategory": "Home Appliances",
        "productName": "Vitamix Explorian Blender",
        "unitsSold": "1",
        "unitPrice": "349.99",
        "totalRevenue": "349.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10099",
        "date": "8/4/2024",
        "productCategory": "Clothing",
        "productName": "Gap Essential Crewneck T-Shirt",
        "unitsSold": "6",
        "unitPrice": "19.99",
        "totalRevenue": "119.94",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10100",
        "date": "9/4/2024",
        "productCategory": "Books",
        "productName": "The Power of Now by Eckhart Tolle",
        "unitsSold": "2",
        "unitPrice": "12.99",
        "totalRevenue": "25.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10101",
        "date": "10/4/2024",
        "productCategory": "Beauty Products",
        "productName": "Kiehl's Midnight Recovery Concentrate",
        "unitsSold": "1",
        "unitPrice": "82",
        "totalRevenue": "82",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10102",
        "date": "11/4/2024",
        "productCategory": "Sports",
        "productName": "Under Armour HOVR Sonic 4 Shoes",
        "unitsSold": "2",
        "unitPrice": "109.99",
        "totalRevenue": "219.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10103",
        "date": "12/4/2024",
        "productCategory": "Electronics",
        "productName": "Canon EOS R5 Camera",
        "unitsSold": "1",
        "unitPrice": "3899.99",
        "totalRevenue": "3899.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10104",
        "date": "13/4/2024",
        "productCategory": "Home Appliances",
        "productName": "Shark IQ Robot Vacuum",
        "unitsSold": "2",
        "unitPrice": "349.99",
        "totalRevenue": "699.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10105",
        "date": "14/4/2024",
        "productCategory": "Clothing",
        "productName": "H&M Slim Fit Jeans",
        "unitsSold": "3",
        "unitPrice": "39.99",
        "totalRevenue": "119.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10106",
        "date": "15/4/2024",
        "productCategory": "Books",
        "productName": "The Girl on the Train by Paula Hawkins",
        "unitsSold": "4",
        "unitPrice": "10.99",
        "totalRevenue": "43.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10107",
        "date": "16/4/2024",
        "productCategory": "Beauty Products",
        "productName": "The Ordinary Niacinamide Serum",
        "unitsSold": "1",
        "unitPrice": "6.5",
        "totalRevenue": "6.5",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10108",
        "date": "17/4/2024",
        "productCategory": "Sports",
        "productName": "Bowflex SelectTech 552 Dumbbells",
        "unitsSold": "1",
        "unitPrice": "399.99",
        "totalRevenue": "399.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10109",
        "date": "18/4/2024",
        "productCategory": "Electronics",
        "productName": "Google Nest Hub Max",
        "unitsSold": "2",
        "unitPrice": "229.99",
        "totalRevenue": "459.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10110",
        "date": "19/4/2024",
        "productCategory": "Home Appliances",
        "productName": "Cuisinart Griddler Deluxe",
        "unitsSold": "1",
        "unitPrice": "159.99",
        "totalRevenue": "159.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10111",
        "date": "20/4/2024",
        "productCategory": "Clothing",
        "productName": "Old Navy Relaxed-Fit T-Shirt",
        "unitsSold": "4",
        "unitPrice": "14.99",
        "totalRevenue": "59.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10112",
        "date": "21/4/2024",
        "productCategory": "Books",
        "productName": "Sapiens: A Brief History of Humankind by Yuval Noah Harari",
        "unitsSold": "2",
        "unitPrice": "18.99",
        "totalRevenue": "37.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10113",
        "date": "22/4/2024",
        "productCategory": "Beauty Products",
        "productName": "Biore UV Aqua Rich Watery Essence Sunscreen",
        "unitsSold": "1",
        "unitPrice": "15",
        "totalRevenue": "15",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10114",
        "date": "23/4/2024",
        "productCategory": "Sports",
        "productName": "Fitbit Versa 3",
        "unitsSold": "3",
        "unitPrice": "229.95",
        "totalRevenue": "689.85",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10115",
        "date": "24/4/2024",
        "productCategory": "Electronics",
        "productName": "Amazon Echo Show 10",
        "unitsSold": "1",
        "unitPrice": "249.99",
        "totalRevenue": "249.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10116",
        "date": "25/4/2024",
        "productCategory": "Home Appliances",
        "productName": "Breville Smart Grill",
        "unitsSold": "2",
        "unitPrice": "299.95",
        "totalRevenue": "599.9",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10117",
        "date": "26/4/2024",
        "productCategory": "Clothing",
        "productName": "Gap High Rise Skinny Jeans",
        "unitsSold": "3",
        "unitPrice": "49.99",
        "totalRevenue": "149.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10118",
        "date": "27/4/2024",
        "productCategory": "Books",
        "productName": "Atomic Habits by James Clear",
        "unitsSold": "4",
        "unitPrice": "16.99",
        "totalRevenue": "67.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10119",
        "date": "28/4/2024",
        "productCategory": "Beauty Products",
        "productName": "CeraVe Hydrating Facial Cleanser",
        "unitsSold": "2",
        "unitPrice": "14.99",
        "totalRevenue": "29.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10120",
        "date": "29/4/2024",
        "productCategory": "Sports",
        "productName": "YETI Hopper Flip Portable Cooler",
        "unitsSold": "1",
        "unitPrice": "249.99",
        "totalRevenue": "249.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10121",
        "date": "30/4/2024",
        "productCategory": "Electronics",
        "productName": "Apple iPad Air",
        "unitsSold": "2",
        "unitPrice": "599.99",
        "totalRevenue": "1199.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10122",
        "date": "1/5/2024",
        "productCategory": "Home Appliances",
        "productName": "Hamilton Beach FlexBrew Coffee Maker",
        "unitsSold": "1",
        "unitPrice": "89.99",
        "totalRevenue": "89.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10123",
        "date": "2/5/2024",
        "productCategory": "Clothing",
        "productName": "Forever 21 Graphic Tee",
        "unitsSold": "5",
        "unitPrice": "12.99",
        "totalRevenue": "64.95",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10124",
        "date": "3/5/2024",
        "productCategory": "Books",
        "productName": "The Subtle Art of Not Giving a F*ck by Mark Manson",
        "unitsSold": "3",
        "unitPrice": "14.99",
        "totalRevenue": "44.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10125",
        "date": "4/5/2024",
        "productCategory": "Beauty Products",
        "productName": "NARS Radiant Creamy Concealer",
        "unitsSold": "1",
        "unitPrice": "30",
        "totalRevenue": "30",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10126",
        "date": "5/5/2024",
        "productCategory": "Sports",
        "productName": "Yeti Roadie 24 Cooler",
        "unitsSold": "1",
        "unitPrice": "199.99",
        "totalRevenue": "199.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10127",
        "date": "6/5/2024",
        "productCategory": "Electronics",
        "productName": "Sony PlayStation 5",
        "unitsSold": "1",
        "unitPrice": "499.99",
        "totalRevenue": "499.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10128",
        "date": "7/5/2024",
        "productCategory": "Home Appliances",
        "productName": "Dyson Supersonic Hair Dryer",
        "unitsSold": "2",
        "unitPrice": "399.99",
        "totalRevenue": "799.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10129",
        "date": "8/5/2024",
        "productCategory": "Clothing",
        "productName": "Lululemon Align Leggings",
        "unitsSold": "3",
        "unitPrice": "98",
        "totalRevenue": "294",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10130",
        "date": "9/5/2024",
        "productCategory": "Books",
        "productName": "The Four Agreements by Don Miguel Ruiz",
        "unitsSold": "2",
        "unitPrice": "8.99",
        "totalRevenue": "17.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10131",
        "date": "10/5/2024",
        "productCategory": "Beauty Products",
        "productName": "Fenty Beauty Killawatt Highlighter",
        "unitsSold": "1",
        "unitPrice": "36",
        "totalRevenue": "36",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10132",
        "date": "11/5/2024",
        "productCategory": "Sports",
        "productName": "Hydro Flask Wide Mouth Water Bottle",
        "unitsSold": "4",
        "unitPrice": "39.95",
        "totalRevenue": "159.8",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10133",
        "date": "12/5/2024",
        "productCategory": "Electronics",
        "productName": "Microsoft Surface Laptop 4",
        "unitsSold": "1",
        "unitPrice": "1299.99",
        "totalRevenue": "1299.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10134",
        "date": "13/5/2024",
        "productCategory": "Home Appliances",
        "productName": "Keurig K-Mini Coffee Maker",
        "unitsSold": "2",
        "unitPrice": "79.99",
        "totalRevenue": "159.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10135",
        "date": "14/5/2024",
        "productCategory": "Clothing",
        "productName": "Gap Crewneck Sweatshirt",
        "unitsSold": "4",
        "unitPrice": "34.99",
        "totalRevenue": "139.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10136",
        "date": "15/5/2024",
        "productCategory": "Books",
        "productName": "Think and Grow Rich by Napoleon Hill",
        "unitsSold": "3",
        "unitPrice": "9.99",
        "totalRevenue": "29.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10137",
        "date": "16/5/2024",
        "productCategory": "Beauty Products",
        "productName": "The Ordinary Hyaluronic Acid Serum",
        "unitsSold": "1",
        "unitPrice": "6.8",
        "totalRevenue": "6.8",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10138",
        "date": "17/5/2024",
        "productCategory": "Sports",
        "productName": "Fitbit Inspire 2",
        "unitsSold": "2",
        "unitPrice": "99.95",
        "totalRevenue": "199.9",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10139",
        "date": "18/5/2024",
        "productCategory": "Electronics",
        "productName": "Samsung Odyssey G9 Gaming Monitor",
        "unitsSold": "1",
        "unitPrice": "1499.99",
        "totalRevenue": "1499.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10140",
        "date": "19/5/2024",
        "productCategory": "Home Appliances",
        "productName": "Instant Pot Ultra",
        "unitsSold": "1",
        "unitPrice": "139.99",
        "totalRevenue": "139.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10141",
        "date": "20/5/2024",
        "productCategory": "Clothing",
        "productName": "Adidas Essential Track Pants",
        "unitsSold": "3",
        "unitPrice": "44.99",
        "totalRevenue": "134.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10142",
        "date": "21/5/2024",
        "productCategory": "Books",
        "productName": "The Power of Habit by Charles Duhigg",
        "unitsSold": "2",
        "unitPrice": "11.99",
        "totalRevenue": "23.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10143",
        "date": "22/5/2024",
        "productCategory": "Beauty Products",
        "productName": "Clinique Dramatically Different Moisturizing Lotion",
        "unitsSold": "1",
        "unitPrice": "29.5",
        "totalRevenue": "29.5",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10144",
        "date": "23/5/2024",
        "productCategory": "Sports",
        "productName": "YETI Tundra 45 Cooler",
        "unitsSold": "1",
        "unitPrice": "299.99",
        "totalRevenue": "299.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10145",
        "date": "24/5/2024",
        "productCategory": "Electronics",
        "productName": "Apple AirPods Max",
        "unitsSold": "1",
        "unitPrice": "549",
        "totalRevenue": "549",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10146",
        "date": "25/5/2024",
        "productCategory": "Home Appliances",
        "productName": "Cuisinart Coffee Center",
        "unitsSold": "2",
        "unitPrice": "199.95",
        "totalRevenue": "399.9",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10147",
        "date": "26/5/2024",
        "productCategory": "Clothing",
        "productName": "Levi's Sherpa Trucker Jacket",
        "unitsSold": "2",
        "unitPrice": "98",
        "totalRevenue": "196",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10148",
        "date": "27/5/2024",
        "productCategory": "Books",
        "productName": "The Outsiders by S.E. Hinton",
        "unitsSold": "3",
        "unitPrice": "10.99",
        "totalRevenue": "32.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10149",
        "date": "28/5/2024",
        "productCategory": "Beauty Products",
        "productName": "Laneige Water Sleeping Mask",
        "unitsSold": "1",
        "unitPrice": "25",
        "totalRevenue": "25",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10150",
        "date": "29/5/2024",
        "productCategory": "Sports",
        "productName": "Bose SoundSport Wireless Earbuds",
        "unitsSold": "2",
        "unitPrice": "149.99",
        "totalRevenue": "299.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10151",
        "date": "30/5/2024",
        "productCategory": "Electronics",
        "productName": "Sony WH-1000XM4 Headphones",
        "unitsSold": "1",
        "unitPrice": "349.99",
        "totalRevenue": "349.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10152",
        "date": "31/5/2024",
        "productCategory": "Home Appliances",
        "productName": "Ninja Foodi Pressure Cooker",
        "unitsSold": "2",
        "unitPrice": "199.99",
        "totalRevenue": "399.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10153",
        "date": "1/6/2024",
        "productCategory": "Clothing",
        "productName": "Nike Sportswear Club Fleece Hoodie",
        "unitsSold": "3",
        "unitPrice": "54.99",
        "totalRevenue": "164.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10154",
        "date": "2/6/2024",
        "productCategory": "Books",
        "productName": "The Night Circus by Erin Morgenstern",
        "unitsSold": "2",
        "unitPrice": "16.99",
        "totalRevenue": "33.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10155",
        "date": "3/6/2024",
        "productCategory": "Beauty Products",
        "productName": "GlamGlow Supermud Clearing Treatment",
        "unitsSold": "1",
        "unitPrice": "59",
        "totalRevenue": "59",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10156",
        "date": "4/6/2024",
        "productCategory": "Sports",
        "productName": "Garmin Forerunner 245",
        "unitsSold": "1",
        "unitPrice": "299.99",
        "totalRevenue": "299.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10157",
        "date": "5/6/2024",
        "productCategory": "Electronics",
        "productName": "Google Pixel 6 Pro",
        "unitsSold": "1",
        "unitPrice": "899.99",
        "totalRevenue": "899.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10158",
        "date": "6/6/2024",
        "productCategory": "Home Appliances",
        "productName": "Breville Nespresso Creatista Plus",
        "unitsSold": "1",
        "unitPrice": "499.95",
        "totalRevenue": "499.95",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10159",
        "date": "7/6/2024",
        "productCategory": "Clothing",
        "productName": "Under Armour Tech 2.0 T-Shirt",
        "unitsSold": "4",
        "unitPrice": "24.99",
        "totalRevenue": "99.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10160",
        "date": "8/6/2024",
        "productCategory": "Books",
        "productName": "The Art of War by Sun Tzu",
        "unitsSold": "3",
        "unitPrice": "7.99",
        "totalRevenue": "23.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10161",
        "date": "9/6/2024",
        "productCategory": "Beauty Products",
        "productName": "Youth to the People Superfood Antioxidant Cleanser",
        "unitsSold": "1",
        "unitPrice": "36",
        "totalRevenue": "36",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10162",
        "date": "10/6/2024",
        "productCategory": "Sports",
        "productName": "TriggerPoint GRID Foam Roller",
        "unitsSold": "2",
        "unitPrice": "34.99",
        "totalRevenue": "69.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10163",
        "date": "11/6/2024",
        "productCategory": "Electronics",
        "productName": "Apple MacBook Air",
        "unitsSold": "1",
        "unitPrice": "1199.99",
        "totalRevenue": "1199.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10164",
        "date": "12/6/2024",
        "productCategory": "Home Appliances",
        "productName": "Cuisinart Custom 14-Cup Food Processor",
        "unitsSold": "1",
        "unitPrice": "199.99",
        "totalRevenue": "199.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10165",
        "date": "13/6/2024",
        "productCategory": "Clothing",
        "productName": "Adidas 3-Stripes Shorts",
        "unitsSold": "5",
        "unitPrice": "29.99",
        "totalRevenue": "149.95",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10166",
        "date": "14/6/2024",
        "productCategory": "Books",
        "productName": "The Hunger Games by Suzanne Collins",
        "unitsSold": "4",
        "unitPrice": "8.99",
        "totalRevenue": "35.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10167",
        "date": "15/6/2024",
        "productCategory": "Beauty Products",
        "productName": "Neutrogena Hydro Boost Water Gel",
        "unitsSold": "1",
        "unitPrice": "16.99",
        "totalRevenue": "16.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10168",
        "date": "16/6/2024",
        "productCategory": "Sports",
        "productName": "Yeti Rambler Bottle",
        "unitsSold": "3",
        "unitPrice": "49.99",
        "totalRevenue": "149.97",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10169",
        "date": "17/6/2024",
        "productCategory": "Electronics",
        "productName": "Samsung Odyssey G7 Gaming Monitor",
        "unitsSold": "1",
        "unitPrice": "699.99",
        "totalRevenue": "699.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10170",
        "date": "18/6/2024",
        "productCategory": "Home Appliances",
        "productName": "Instant Pot Duo Evo Plus",
        "unitsSold": "2",
        "unitPrice": "139.99",
        "totalRevenue": "279.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10171",
        "date": "19/6/2024",
        "productCategory": "Clothing",
        "productName": "Nike Tempo Running Shorts",
        "unitsSold": "3",
        "unitPrice": "34.99",
        "totalRevenue": "104.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10172",
        "date": "20/6/2024",
        "productCategory": "Books",
        "productName": "The Girl with the Dragon Tattoo by Stieg Larsson",
        "unitsSold": "2",
        "unitPrice": "9.99",
        "totalRevenue": "19.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10173",
        "date": "21/6/2024",
        "productCategory": "Beauty Products",
        "productName": "Paula's Choice Skin Perfecting 2% BHA Liquid Exfoliant",
        "unitsSold": "1",
        "unitPrice": "29.5",
        "totalRevenue": "29.5",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10174",
        "date": "22/6/2024",
        "productCategory": "Sports",
        "productName": "Bowflex SelectTech 1090 Adjustable Dumbbells",
        "unitsSold": "1",
        "unitPrice": "699.99",
        "totalRevenue": "699.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10175",
        "date": "23/6/2024",
        "productCategory": "Electronics",
        "productName": "Amazon Fire TV Stick 4K",
        "unitsSold": "3",
        "unitPrice": "49.99",
        "totalRevenue": "149.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10176",
        "date": "24/6/2024",
        "productCategory": "Home Appliances",
        "productName": "Crock-Pot 6-Quart Slow Cooker",
        "unitsSold": "2",
        "unitPrice": "49.99",
        "totalRevenue": "99.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10177",
        "date": "25/6/2024",
        "productCategory": "Clothing",
        "productName": "Uniqlo Airism Mesh Boxer Briefs",
        "unitsSold": "4",
        "unitPrice": "14.9",
        "totalRevenue": "59.6",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10178",
        "date": "26/6/2024",
        "productCategory": "Books",
        "productName": "The Sun Also Rises by Ernest Hemingway",
        "unitsSold": "3",
        "unitPrice": "11.99",
        "totalRevenue": "35.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10179",
        "date": "27/6/2024",
        "productCategory": "Beauty Products",
        "productName": "First Aid Beauty Ultra Repair Cream",
        "unitsSold": "2",
        "unitPrice": "34",
        "totalRevenue": "68",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10180",
        "date": "28/6/2024",
        "productCategory": "Sports",
        "productName": "Oakley Holbrook Sunglasses",
        "unitsSold": "1",
        "unitPrice": "146",
        "totalRevenue": "146",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10181",
        "date": "29/6/2024",
        "productCategory": "Electronics",
        "productName": "Google Pixelbook Go",
        "unitsSold": "1",
        "unitPrice": "649.99",
        "totalRevenue": "649.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10182",
        "date": "30/6/2024",
        "productCategory": "Home Appliances",
        "productName": "Dyson V8 Absolute",
        "unitsSold": "1",
        "unitPrice": "399.99",
        "totalRevenue": "399.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10183",
        "date": "1/7/2024",
        "productCategory": "Clothing",
        "productName": "Levi's 511 Slim Fit Jeans",
        "unitsSold": "3",
        "unitPrice": "59.99",
        "totalRevenue": "179.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10184",
        "date": "2/7/2024",
        "productCategory": "Books",
        "productName": "The Martian by Andy Weir",
        "unitsSold": "2",
        "unitPrice": "12.99",
        "totalRevenue": "25.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10185",
        "date": "3/7/2024",
        "productCategory": "Beauty Products",
        "productName": "La Mer Crème de la Mer Moisturizer",
        "unitsSold": "1",
        "unitPrice": "190",
        "totalRevenue": "190",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10186",
        "date": "4/7/2024",
        "productCategory": "Sports",
        "productName": "Polar Vantage V2",
        "unitsSold": "1",
        "unitPrice": "499.95",
        "totalRevenue": "499.95",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10187",
        "date": "5/7/2024",
        "productCategory": "Electronics",
        "productName": "Sonos Beam Soundbar",
        "unitsSold": "1",
        "unitPrice": "399",
        "totalRevenue": "399",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10188",
        "date": "6/7/2024",
        "productCategory": "Home Appliances",
        "productName": "Anova Precision Cooker",
        "unitsSold": "2",
        "unitPrice": "199",
        "totalRevenue": "398",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10189",
        "date": "7/7/2024",
        "productCategory": "Clothing",
        "productName": "Nike Dri-FIT Training Shorts",
        "unitsSold": "4",
        "unitPrice": "34.99",
        "totalRevenue": "139.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10190",
        "date": "8/7/2024",
        "productCategory": "Books",
        "productName": "The Catcher in the Rye by J.D. Salinger",
        "unitsSold": "3",
        "unitPrice": "10.99",
        "totalRevenue": "32.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10191",
        "date": "9/7/2024",
        "productCategory": "Beauty Products",
        "productName": "Glossier Cloud Paint",
        "unitsSold": "1",
        "unitPrice": "18",
        "totalRevenue": "18",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10192",
        "date": "10/7/2024",
        "productCategory": "Sports",
        "productName": "TRX All-in-One Suspension Training System",
        "unitsSold": "1",
        "unitPrice": "169.95",
        "totalRevenue": "169.95",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10193",
        "date": "11/7/2024",
        "productCategory": "Electronics",
        "productName": "Logitech G Pro X Wireless Gaming Headset",
        "unitsSold": "1",
        "unitPrice": "199.99",
        "totalRevenue": "199.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10194",
        "date": "12/7/2024",
        "productCategory": "Home Appliances",
        "productName": "Breville Smart Coffee Grinder Pro",
        "unitsSold": "1",
        "unitPrice": "199.95",
        "totalRevenue": "199.95",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10195",
        "date": "13/7/2024",
        "productCategory": "Clothing",
        "productName": "Adidas Ultraboost Running Shoes",
        "unitsSold": "2",
        "unitPrice": "179.99",
        "totalRevenue": "359.98",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10196",
        "date": "14/7/2024",
        "productCategory": "Books",
        "productName": "The Road by Cormac McCarthy",
        "unitsSold": "2",
        "unitPrice": "11.99",
        "totalRevenue": "23.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10197",
        "date": "15/7/2024",
        "productCategory": "Beauty Products",
        "productName": "Tom Ford Black Orchid Perfume",
        "unitsSold": "1",
        "unitPrice": "125",
        "totalRevenue": "125",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10198",
        "date": "16/7/2024",
        "productCategory": "Sports",
        "productName": "GoPro HERO9 Black",
        "unitsSold": "1",
        "unitPrice": "449.99",
        "totalRevenue": "449.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10199",
        "date": "17/7/2024",
        "productCategory": "Electronics",
        "productName": "Apple TV 4K",
        "unitsSold": "2",
        "unitPrice": "179",
        "totalRevenue": "358",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10200",
        "date": "18/7/2024",
        "productCategory": "Home Appliances",
        "productName": "Instant Pot Duo Nova",
        "unitsSold": "1",
        "unitPrice": "99.95",
        "totalRevenue": "99.95",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10201",
        "date": "19/7/2024",
        "productCategory": "Clothing",
        "productName": "Gap 1969 Original Fit Jeans",
        "unitsSold": "3",
        "unitPrice": "59.99",
        "totalRevenue": "179.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10202",
        "date": "20/7/2024",
        "productCategory": "Books",
        "productName": "The Goldfinch by Donna Tartt",
        "unitsSold": "2",
        "unitPrice": "14.99",
        "totalRevenue": "29.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10203",
        "date": "21/7/2024",
        "productCategory": "Beauty Products",
        "productName": "Dr. Jart+ Cicapair Tiger Grass Color Correcting Treatment",
        "unitsSold": "1",
        "unitPrice": "52",
        "totalRevenue": "52",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10204",
        "date": "22/7/2024",
        "productCategory": "Sports",
        "productName": "Yeti Tundra Haul Portable Wheeled Cooler",
        "unitsSold": "1",
        "unitPrice": "399.99",
        "totalRevenue": "399.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10205",
        "date": "23/7/2024",
        "productCategory": "Electronics",
        "productName": "Samsung Galaxy Watch 4",
        "unitsSold": "1",
        "unitPrice": "299.99",
        "totalRevenue": "299.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10206",
        "date": "24/7/2024",
        "productCategory": "Home Appliances",
        "productName": "KitchenAid Stand Mixer",
        "unitsSold": "1",
        "unitPrice": "379.99",
        "totalRevenue": "379.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10207",
        "date": "25/7/2024",
        "productCategory": "Clothing",
        "productName": "Lululemon Wunder Under High-Rise Leggings",
        "unitsSold": "2",
        "unitPrice": "98",
        "totalRevenue": "196",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10208",
        "date": "26/7/2024",
        "productCategory": "Books",
        "productName": "The Great Alone by Kristin Hannah",
        "unitsSold": "3",
        "unitPrice": "16.99",
        "totalRevenue": "50.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10209",
        "date": "27/7/2024",
        "productCategory": "Beauty Products",
        "productName": "Caudalie Vinoperfect Radiance Serum",
        "unitsSold": "1",
        "unitPrice": "79",
        "totalRevenue": "79",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10210",
        "date": "28/7/2024",
        "productCategory": "Sports",
        "productName": "Bose SoundLink Color Bluetooth Speaker II",
        "unitsSold": "1",
        "unitPrice": "129",
        "totalRevenue": "129",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10211",
        "date": "29/7/2024",
        "productCategory": "Electronics",
        "productName": "Canon EOS Rebel T7i DSLR Camera",
        "unitsSold": "1",
        "unitPrice": "749.99",
        "totalRevenue": "749.99",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10212",
        "date": "30/7/2024",
        "productCategory": "Home Appliances",
        "productName": "Keurig K-Elite Coffee Maker",
        "unitsSold": "2",
        "unitPrice": "169.99",
        "totalRevenue": "339.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10213",
        "date": "31/7/2024",
        "productCategory": "Clothing",
        "productName": "Uniqlo Airism Seamless Boxer Briefs",
        "unitsSold": "4",
        "unitPrice": "9.9",
        "totalRevenue": "39.6",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10214",
        "date": "1/8/2024",
        "productCategory": "Books",
        "productName": "The Girl with the Dragon Tattoo by Stieg Larsson",
        "unitsSold": "3",
        "unitPrice": "10.99",
        "totalRevenue": "32.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10215",
        "date": "2/8/2024",
        "productCategory": "Beauty Products",
        "productName": "L'Occitane Shea Butter Hand Cream",
        "unitsSold": "2",
        "unitPrice": "29",
        "totalRevenue": "58",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10216",
        "date": "3/8/2024",
        "productCategory": "Sports",
        "productName": "YETI Tundra 65 Cooler",
        "unitsSold": "1",
        "unitPrice": "349.99",
        "totalRevenue": "349.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10217",
        "date": "4/8/2024",
        "productCategory": "Electronics",
        "productName": "Apple MacBook Pro 16-inch",
        "unitsSold": "1",
        "unitPrice": "2399",
        "totalRevenue": "2399",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10218",
        "date": "5/8/2024",
        "productCategory": "Home Appliances",
        "productName": "iRobot Braava Jet M6",
        "unitsSold": "1",
        "unitPrice": "449.99",
        "totalRevenue": "449.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10219",
        "date": "6/8/2024",
        "productCategory": "Clothing",
        "productName": "Champion Reverse Weave Hoodie",
        "unitsSold": "3",
        "unitPrice": "49.99",
        "totalRevenue": "149.97",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10220",
        "date": "7/8/2024",
        "productCategory": "Books",
        "productName": "The Nightingale by Kristin Hannah",
        "unitsSold": "2",
        "unitPrice": "12.99",
        "totalRevenue": "25.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10221",
        "date": "8/8/2024",
        "productCategory": "Beauty Products",
        "productName": "Tarte Shape Tape Concealer",
        "unitsSold": "1",
        "unitPrice": "27",
        "totalRevenue": "27",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10222",
        "date": "9/8/2024",
        "productCategory": "Sports",
        "productName": "Garmin Forerunner 945",
        "unitsSold": "1",
        "unitPrice": "599.99",
        "totalRevenue": "599.99",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10223",
        "date": "10/8/2024",
        "productCategory": "Electronics",
        "productName": "Amazon Echo Dot (4th Gen)",
        "unitsSold": "4",
        "unitPrice": "49.99",
        "totalRevenue": "199.96",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10224",
        "date": "11/8/2024",
        "productCategory": "Home Appliances",
        "productName": "Philips Sonicare DiamondClean Toothbrush",
        "unitsSold": "2",
        "unitPrice": "229.99",
        "totalRevenue": "459.98",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10225",
        "date": "12/8/2024",
        "productCategory": "Clothing",
        "productName": "Old Navy Mid-Rise Rockstar Super Skinny Jeans",
        "unitsSold": "2",
        "unitPrice": "44.99",
        "totalRevenue": "89.98",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10226",
        "date": "13/8/2024",
        "productCategory": "Books",
        "productName": "The Silent Patient by Alex Michaelides",
        "unitsSold": "3",
        "unitPrice": "26.99",
        "totalRevenue": "80.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10227",
        "date": "14/8/2024",
        "productCategory": "Beauty Products",
        "productName": "The Ordinary Caffeine Solution 5% + EGCG",
        "unitsSold": "1",
        "unitPrice": "6.7",
        "totalRevenue": "6.7",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10228",
        "date": "15/8/2024",
        "productCategory": "Sports",
        "productName": "Fitbit Luxe",
        "unitsSold": "2",
        "unitPrice": "149.95",
        "totalRevenue": "299.9",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10229",
        "date": "16/8/2024",
        "productCategory": "Electronics",
        "productName": "Google Nest Wifi Router",
        "unitsSold": "1",
        "unitPrice": "169",
        "totalRevenue": "169",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10230",
        "date": "17/8/2024",
        "productCategory": "Home Appliances",
        "productName": "Anova Precision Oven",
        "unitsSold": "1",
        "unitPrice": "599",
        "totalRevenue": "599",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10231",
        "date": "18/8/2024",
        "productCategory": "Clothing",
        "productName": "Adidas Originals Trefoil Hoodie",
        "unitsSold": "4",
        "unitPrice": "64.99",
        "totalRevenue": "259.96",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10232",
        "date": "19/8/2024",
        "productCategory": "Books",
        "productName": "Dune by Frank Herbert",
        "unitsSold": "2",
        "unitPrice": "9.99",
        "totalRevenue": "19.98",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10233",
        "date": "20/8/2024",
        "productCategory": "Beauty Products",
        "productName": "Fresh Sugar Lip Treatment",
        "unitsSold": "1",
        "unitPrice": "24",
        "totalRevenue": "24",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10234",
        "date": "21/8/2024",
        "productCategory": "Sports",
        "productName": "Hydro Flask Standard Mouth Water Bottle",
        "unitsSold": "3",
        "unitPrice": "32.95",
        "totalRevenue": "98.85",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10235",
        "date": "22/8/2024",
        "productCategory": "Electronics",
        "productName": "Bose QuietComfort 35 II Wireless Headphones",
        "unitsSold": "1",
        "unitPrice": "299",
        "totalRevenue": "299",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10236",
        "date": "23/8/2024",
        "productCategory": "Home Appliances",
        "productName": "Nespresso Vertuo Next Coffee and Espresso Maker",
        "unitsSold": "1",
        "unitPrice": "159.99",
        "totalRevenue": "159.99",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10237",
        "date": "24/8/2024",
        "productCategory": "Clothing",
        "productName": "Nike Air Force 1 Sneakers",
        "unitsSold": "3",
        "unitPrice": "90",
        "totalRevenue": "270",
        "region": "Asia",
        "paymentMethod": "Debit Card"
    },
    {
        "transactionID": "10238",
        "date": "25/8/2024",
        "productCategory": "Books",
        "productName": "The Handmaid's Tale by Margaret Atwood",
        "unitsSold": "3",
        "unitPrice": "10.99",
        "totalRevenue": "32.97",
        "region": "North America",
        "paymentMethod": "Credit Card"
    },
    {
        "transactionID": "10239",
        "date": "26/8/2024",
        "productCategory": "Beauty Products",
        "productName": "Sunday Riley Luna Sleeping Night Oil",
        "unitsSold": "1",
        "unitPrice": "55",
        "totalRevenue": "55",
        "region": "Europe",
        "paymentMethod": "PayPal"
    },
    {
        "transactionID": "10240",
        "date": "27/8/2024",
        "productCategory": "Sports",
        "productName": "Yeti Rambler 20 oz Tumbler",
        "unitsSold": "2",
        "unitPrice": "29.99",
        "totalRevenue": "59.98",
        "region": "Asia",
        "paymentMethod": "Credit Card"
    }
];